# Generated by Django 2.2 on 2019-04-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='created_app',
            new_name='created_at',
        ),
    ]
